- name: variables in ansible
  hosts: mongodb
  vars:
    COURSE: DevOps with AWS
    TRAINER: Madeen
    DURATION: 90hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"      
