- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  vars:
  - money: "1000 rs"
    land: "4 acers"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add override
    vars:
    - money: "2000 rs"
      houses: "4 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"
              
