- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # when you want to run linux commands directly i.e. in case ansible module is not available
    # when the user doesnot exists, ansible treatig this failure and comout by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output # output is variable name
    ignore_errors: true
  - name: print the commnad output
    ansible.builtin.debug:
      msg: "output is: {{output}}"  
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"     
