- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # when you want to run linux commands directly i.e. in case ansible module is not available
    ansible.builtin.command: id roboshop
    register: output # output is variable name
  - name: print the commnad output
    ansible.builtin.debug:
      msg: "output is: {{output}}"  
