- name: ansible variable data types
  hosts: localhost
  vars:
  - AGE: 30 #number
  - NAME: madeen #string
  - isDevOps: true #boolean
  - Skills: #list
    - Devops
    - AWS
    - Ansible
  - Experience: #map
      Devops: 7
      AWS: 4
      Ansible: 2
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "{{AGE}}"
  - name: print string variable
    ansible.builtin.debug:
      msg: "{{NAME}}"
  - name: print boolean variable
    ansible.builtin.debug:
      msg: "{{isDevOps}}"
  - name: print list variable
    ansible.builin.debug:
      msg: "{{Skills}}"
  - name: print map variable
    ansible.builtin.debug:
      msg: "{{Experience}}"                   
