- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
     msg: "{{item}}"
     state: prsent
    loop:
    - nginx
    - git
    - postfix 

    